export const columns1 = [
  {
    title: "이수 학년",
    dataIndex: "a",
    filters: [
      {
        text: "1학년",
        value: "1학년",
      },
      {
        text: "2학년",
        value: "2학년",
      },
      {
        text: "3학년",
        value: "3학년",
      },
      {
        text: "4학년",
        value: "4학년",
      },
    ],
    onFilter: (value, record) => record.a.indexOf(value) === 0,
    width: "150px",
  },
  {
    title: "과목명",
    dataIndex: "subject",
    render: (text) => <a>{text}</a>,
  },
  {
    title: "학점",
    dataIndex: "grade",
  },
  {
    title: "설계학점",
    dataIndex: "DesignCredits",
  },
  {
    title: "전공필수",
    dataIndex: "must",
  },
  {
    title: "이수트랙",
    dataIndex: "track",
  },
];

export const columns2 = [
  {
    title: "과목명",
    dataIndex: "subject",
    render: (text) => <a>{text}</a>,
  },
  {
    title: "학점",
    dataIndex: "grade",
  },
];

export const columns3 = [
  {
    title: "과목명",
    dataIndex: "subject",
    render: (text) => <a>{text}</a>,
  },
  {
    title: "학점",
    dataIndex: "grade",
  },
];

export const major = [
  {
    key: "1",
    a: "1학년",
    subject: "산업경영공학전공및진로탐색",
    grade: 1,
    DesignCredits: "",
    must: "필수",
    track: "",
  },
  {
    key: "2",
    a: "1학년",
    subject: "창의공학설계",
    grade: 3,
    DesignCredits: "3",
    must: "",
    track: "",
  },
  {
    key: "3",
    a: "1학년",
    subject: "산업경영공학개론",
    grade: 3,
    DesignCredits: "3",
    must: "",
    track: "",
  },
  {
    key: "4",
    a: "2학년",
    subject: "경영과학1 및 실습",
    grade: 3,
    DesignCredits: "",
    must: "필수",
    track: "시스템분석/경영공학",
  },
  {
    key: "5",
    a: "2학년",
    subject: "경제성공학",
    grade: 3,
    DesignCredits: "",
    must: "",
    track: "시스템분석/경영공학",
  },
  {
    key: "6",
    a: "2학년",
    subject: "공학통계1",
    grade: 3,
    DesignCredits: "",
    must: "필수",
    track: "",
  },
  {
    key: "7",
    a: "2학년",
    subject: "산업자료관리",
    grade: 3,
    DesignCredits: "1",
    must: "필수",
    track: "품질/정보",
  },
  {
    key: "8",
    a: "2학년",
    subject: "작업분석 및 설계",
    grade: 3,
    DesignCredits: "1",
    track: "생산/물류/인간공학",
  },
  {
    key: "9",
    a: "2학년",
    subject: "공학통계2",
    grade: 3,
    DesignCredits: "",
    must: "",
    track: "",
  },
  {
    key: "10",
    a: "2학년",
    subject: "통계적 품질관리",
    grade: 3,
    DesignCredits: "1",
    must: "필수",
    track: "품질/정보",
  },
  {
    key: "11",
    a: "2학년",
    subject: "프로그래밍응용",
    grade: 3,
    DesignCredits: "1",
    track: "품질/정보",
  },
  {
    key: "12",
    a: "2학년",
    subject: "물류경영",
    grade: 3,
    DesignCredits: "",
    must: "",
    track: "생산/물류/인간공학",
  },
  {
    key: "13",
    a: "2학년",
    subject: "생산계획",
    grade: 3,
    DesignCredits: "",
    must: "필수",
    track: "생산/물류/인간공학",
  },
  {
    key: "14",
    a: "3학년",
    subject: "서비스경영",
    grade: 3,
    DesignCredits: "1",
    must: "필수",
    track: "시스템분석/경영공학",
  },
  {
    key: "15",
    a: "3학년",
    subject: "경영과학2",
    grade: 3,
    DesignCredits: "",
    must: "",
    track: "시스템분석/경영공학",
  },
  {
    key: "16",
    a: "3학년",
    subject: "데이터마이닝",
    grade: 3,
    DesignCredits: "",
    must: "",
    track: "시스템분석/경영공학",
  },
  {
    key: "17",
    a: "3학년",
    subject: "실험계획법응용",
    grade: 3,
    DesignCredits: "",
    must: "",
    track: "품질/정보",
  },
  {
    key: "18",
    a: "3학년",
    subject: "시스템분석 및 설계",
    grade: 3,
    DesignCredits: "",
    must: "",
    track: "품질/정보",
  },
  {
    key: "19",
    a: "3학년",
    subject: "생산통제",
    grade: 3,
    DesignCredits: "",
    must: "필수",
    track: "생산/물류/인간공학",
  },
  {
    key: "20",
    a: "3학년",
    subject: "시뮬레이션 및 실습",
    grade: 3,
    DesignCredits: "1",
    track: "시스템분석/경영공학",
  },
  {
    key: "21",
    a: "3학년",
    subject: "의사결정분석",
    grade: 3,
    DesignCredits: "1",
    track: "시스템분석/경영공학",
  },
  {
    key: "22",
    a: "3학년",
    subject: "원가및재무공학",
    grade: 3,
    DesignCredits: "",
    must: "",
    track: "시스템분석/경영공학",
  },
  {
    key: "23",
    a: "3학년",
    subject: "신뢰성공학",
    grade: 3,
    DesignCredits: "",
    must: "",
    track: "품질/정보",
  },
  {
    key: "24",
    a: "3학년",
    subject: "6시그마품질",
    grade: 3,
    DesignCredits: "1",
    track: "품질/정보",
  },
  {
    key: "25",
    a: "3학년",
    subject: "SCM/ERP",
    grade: 3,
    DesignCredits: "",
    must: "",
    track: "생산/물류/인간공학",
  },
  {
    key: "26",
    a: "3학년",
    subject: "산영경영공학개별진로연구",
    grade: 1,
    DesignCredits: "",
    must: "",
    track: "",
  },
  {
    key: "27",
    a: "4학년",
    subject: "품질경영",
    grade: 3,
    DesignCredits: "",
    must: "",
    track: "품질/정보",
  },
  {
    key: "28",
    a: "4학년",
    subject: "생산물류",
    grade: 3,
    DesignCredits: "",
    must: "",
    track: "생산/물류/인간공학",
  },
  {
    key: "29",
    a: "4학년",
    subject: "인간공학 및 실험",
    grade: 3,
    DesignCredits: "1",
    track: "생산/물류/인간공학",
  },
  {
    key: "30",
    a: "4학년",
    subject: "산업경영공학종합설계",
    grade: 3,
    DesignCredits: "3",
    track: "",
  },
  {
    key: "31",
    a: "4학년",
    subject: "기술경영론",
    grade: 3,
    DesignCredits: "",
    must: "",
    track: "시스템분석/경영공학",
  },
  {
    key: "32",
    a: "4학년",
    subject: "통계자료분석사례연구",
    grade: 3,
    DesignCredits: "",
    must: "",
    track: "품질/정보",
  },
  {
    key: "33",
    a: "4학년",
    subject: "산업정보시스템",
    grade: 3,
    DesignCredits: "",
    must: "",
    track: "품질/정보",
  },
  {
    key: "34",
    a: "4학년",
    subject: "제품 설계 및 개발",
    grade: 3,
    DesignCredits: "",
    must: "",
    track: "생산/물류/인간공학",
  },
];

export const refinement = [
  {
    key: "1",
    subject: "미분적분학",
    grade: 3,
  },
  {
    key: "2",
    subject: "공학수학1",
    grade: 3,
  },
  {
    key: "3",
    subject: "공학수학2",
    grade: 3,
  },
  {
    key: "4",
    subject: "공학통계개론",
    grade: 3,
  },
  {
    key: "5",
    subject: "공학수치해석",
    grade: 3,
  },
  {
    key: "6",
    subject: "공학선형대수",
    grade: 3,
  },
  {
    key: "7",
    subject: "공학물리학및실험1",
    grade: 3,
  },
  {
    key: "8",
    subject: "공학물리학및실험2",
    grade: 3,
  },
  {
    key: "9",
    subject: "공학화학및실험1",
    grade: 3,
  },
  {
    key: "10",
    subject: "공학화학및실험2",
    grade: 3,
  },
  {
    key: "11",
    subject: "지구시스템과학",
    grade: 3,
  },
  {
    key: "12",
    subject: "생명과학",
    grade: 3,
  },
  {
    key: "13",
    subject: "프로그래밍기초와실습",
    grade: 3,
  },
  {
    key: "14",
    subject: "공학컴퓨터프로그래밍",
    grade: 3,
  },
];

export const common = [
  {
    key: "1",
    subject: "진",
    grade: 2,
  },
  {
    key: "2",
    subject: "성",
    grade: 2,
  },
  {
    key: "3",
    subject: "애",
    grade: 2,
  },
  {
    key: "4",
    subject: "사고와표현",
    grade: 3,
  },
  {
    key: "5",
    subject: "대학영어1",
    grade: 3,
  },
  {
    key: "6",
    subject: "대학영어2",
    grade: 3,
  },
  {
    key: "7",
    subject: "중국어회화",
    grade: 3,
  },
  {
    key: "8",
    subject: "중국어입문",
    grade: 3,
  },
  {
    key: "9",
    subject: "일본어회화",
    grade: 3,
  },
  {
    key: "10",
    subject: "일본어입문",
    grade: 3,
  },
  {
    key: "11",
    subject: "독일어회화",
    grade: 3,
  },
  {
    key: "12",
    subject: "독일어입문",
    grade: 3,
  },
  {
    key: "13",
    subject: "프랑스어입문",
    grade: 3,
  },
  {
    key: "14",
    subject: "러시아어입문",
    grade: 3,
  },
  {
    key: "15",
    subject: "러시아회화",
    grade: 3,
  },
  {
    key: "16",
    subject: "공학윤리",
    grade: 3,
  },
  {
    key: "17",
    subject: "특허와 기술개발",
    grade: 3,
  },
];
